
const MessageConstants = {
    MSG_CAMPOS_INCOMPLETOS: 'DATOS INCOMPLETOS',
    MSG_GUARDADO_FALLIDO: 'NO SE GUARDARON LOS DATOS :(',
    MSG_DATOS_GUARDADOS: 'DATOS GUARDADOS CON EXITO :)',
    MSG_TELEFONO_UNDEFINED: 'NO HAY NUMERO DE EMERGENCIA.'
}
export default MessageConstants;